spring:
  mail:
    #\u914D\u7F6E\u53D1\u9001\u65B9\u534F\u8BAE
    protocol: smtp
    #\u914D\u7F6Esmtp\u670D\u52A1\u5668\u5730\u5740
    host: smtp.sina.com
    #\u53D1\u9001\u65B9\u7684\u90AE\u7BB1
    username: qingdumeilingzi@sina.com
    #\u53D1\u9001\u65B9\u7684\u5BC6\u7801
    password: x082713409

spring:
  datasource:
    url: jdbc:mysql:///xl
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
dubbo:
  application:
    name: mail_service
  registry:
    address: zookeeper://192.168.225.0:2181
  protocol:
    port: -1
  consumer:
    check: false

