spring:
  datasource:
    url: jdbc:mysql:///xl
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
dubbo:
  application:
    name: rl_service
  registry:
    address: zookeeper://192.168.225.0:2181
  protocol:
    port: -1
  consumer:
    check: false
